INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Matheus Sia', '16', 'Ensino Médio', '2º', 'matheus@email.com', '123.321.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Felippe Sia', '10', 'Ensino Fundamental', '4º', 'felippe@email.com', '321.321.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Rodrigo Ferreira', '15', 'Ensino Médio', '2º', 'rodrigo@email.com', '123.321.123-33');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Fernando Ribeiro', '12', 'Ensino Fundamental', '7º', 'fernanda@email.com', '321.781.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Francisco Alvarenga', '15', 'Ensino Médio', '1º', 'francisco@email.com', '987.321.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Ronaldo Junior', '16', 'Ensino Médio', '2º', 'ronaldo@email.com', '789.321.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Sebastião dos Santos', '11', 'Ensino Fundamental', '6º', 'sebastiao@email.com', '871.321.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Nathalia Cintra', '13', 'Ensino Fundamental', '8º', 'nathalia@email.com', '123.456.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Rachel Lima', '15', 'Ensino Médio', '1º', 'rachel@email.com', '123.654.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Valentina Duarte', '17', 'Ensino Médio', '3º', 'valentina@email.com', '321.546.123-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Stefani Rio', '11', 'Ensino Fundamental', '6º', 'stefani@email.com', '123.321.654-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Brunna Cavalcante', '12', 'Ensino Fundamental', '7º', 'brunna@email.com', '123.321.456-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Leticia Lima', '14', 'Ensino Fundamental', '9º', 'leticia@email.com', '321.321.987-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Eduarda Ferreira', '16', 'Ensino Médio', '2º', 'eduarda@email.com', '123.321.789-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Eduardo Nunes', '16', 'Ensino Médio', '2º', 'eduardo@email.com', '123.321.879-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Jose Felipe', '12', 'Ensino Fundamental', '7º', 'jose@email.com', '321.321.123-44');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Carlos Albuquerque', '11', 'Ensino Fundamental', '6º', 'carlos@email.com', '123.321.123-55');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Paulo Donatello', '17', 'Ensino Médio', '3º', 'paulo@email.com', '123.321.123-66');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Lucas Andrade', '15', 'Ensino Médio', '1º', 'lucas@email.com', '321.321.123-77');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Joana Da Cunha', '14', 'Ensino Fundamental', '9º', 'joana@email.com', '123.321.123-88');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Silvana Nunes', '13', 'Ensino Fundamental', '8º', 'silvana@email.com', '123.321.123-99');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Cristiane Lima', '11', 'Ensino Fundamental', '6º', 'cristiane@email.com', '321.456.123-99');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Heloisa Xavier', '12', 'Ensino Fundamental', '7º', 'heloisa@email.com', '987.321.123-88');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Alexis Sobral', '16', 'Ensino Médio', '2º', 'alexis@email.com', '123.012.123-23');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Alexandre Roberto', '17', 'Ensino Médio', '3º', 'alexandre@email.com', '321.321.123-65');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Isabella Vieira', '12', 'Ensino Fundamental', '7º', 'isabella@email.com', '123.321.123-98');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Roberto Junior', '17', 'Ensino Médio', '3º', 'roberto@email.com', '123.321.373-75');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Estevam da Silva', '16', 'Ensino Médio', '2º', 'estevam@email.com', '357.321.764-22');
INSERT INTO ALUNO(nome, idade, ensino, serie, email, cpf) VALUES('Pedro Otavio', '15', 'Ensino Médio', '1º', 'pedro@email.com', '333.321.123-68');